# Generated by Django 5.1.3 on 2024-11-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('factura', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('idcliente', models.CharField(max_length=100)),
                ('idproducto', models.CharField(max_length=60)),
                ('idempleado', models.CharField(max_length=60)),
                ('fecha', models.DateField(max_length=60)),
                ('cantidad', models.PositiveIntegerField()),
                ('metodo', models.CharField(max_length=60)),
            ],
        ),
    ]
