# Generated by Django 5.1.3 on 2024-11-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_rename_idproducto_venta_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='idempleado',
            new_name='empleado',
        ),
    ]
