# Generated by Django 5.1 on 2024-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_rename_idempleado_venta_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='factura',
            field=models.PositiveSmallIntegerField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='idcliente',
            field=models.PositiveSmallIntegerField(max_length=100),
        ),
    ]
