# Generated by Django 5.1.3 on 2024-11-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=60)),
                ('horario', models.TimeField(max_length=60)),
                ('salario', models.PositiveSmallIntegerField()),
                ('experiencia', models.CharField(max_length=60)),
                ('certificaciones', models.CharField(max_length=60)),
            ],
        ),
    ]
