# Generated by Django 5.1.3 on 2024-11-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.PositiveSmallIntegerField()),
                ('direccion', models.CharField(max_length=60)),
                ('interes', models.PositiveSmallIntegerField()),
                ('historial', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
    ]
